### ISSUE TITLE
More errors

### ISSUE THREAD

**Issue by hlkn** [ArrowElectronics/aws-iot-dragonconnect-c#4]
Hi There

The installation is doing well (attached in the note below the signature) for a bit more and then hit more errors:

Running "createMultiTask:audioEvents" (createMultiTask) task
Unhandled rejection InvalidClientTokenId: The security token included in the request is invalid.
    at Request.extractError (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/linaro/Documents/arrow/aws-iot-dragonconnect-c/lambda/node_modules/aws-sdk/lib/request.js:38:9)

***Configuring Amazon API gateway...

A client error (InvalidClientTokenId) occurred when calling the ListRoles operation: The security token included in the request is invalid.
#### Detected  as API Gateway Extension
Picked up JAVA_TOOL_OPTIONS: -Dgnu.io.rxtx.SerialPorts=/dev/tty96B0
2016-06-07 03:22:37,526 INFO - Using API Gateway endpoint https://apigateway.us-west-2.amazonaws.com
2016-06-07 03:22:45,896 ERROR - Error importing API definition
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.amazonaws.AmazonServiceException: The security token included in the request is invalid. (Service: null; Status Code: 403; Error Code: null; Request ID: 1a39a755-2c5f-11e6-ab04-df3157e3cab5)
  at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:63)
  while locating com.amazonaws.services.apigateway.model.ApiGateway
    for field at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.apiGateway(ApiGatewaySdkApiImporter.java:41)
  while locating com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter
  while locating com.amazonaws.service.apigateway.importer.SwaggerApiImporter
    for parameter 1 at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.<init>(ApiGatewaySwaggerFileImporter.java:36)
  while locating com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:143)
	at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
Caused by: com.amazonaws.AmazonServiceException: The security token included in the request is invalid. (Service: null; Status Code: 403; Error Code: null; Request ID: 1a39a755-2c5f-11e6-ab04-df3157e3cab5)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1275)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:873)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
	at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
	at com.amazonaws.hal.client.HalClient.getHalResource(HalClient.java:210)
	at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:200)
	at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:92)
	at com.amazonaws.hal.HalService.getRootResource(HalService.java:128)
	at com.amazonaws.services.apigateway.AmazonApiGateway.getApiGateway(AmazonApiGateway.java:113)
	at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:299)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 3 more

Regards, Henry

**Comment by hlkn** [comment]
I believe I know the issue - One MUST login as root account to perform the installation tasks... Not as an IAM account....
