### ISSUE TITLE
and then more issue with s3 upload

### ISSUE THREAD

**Issue by hlkn** [ArrowElectronics/aws-iot-dragonconnect-c#5]
Hi there

***Configuring Amazon API gateway...

A client error (InvalidClientTokenId) occurred when calling the ListRoles operation: The security token included in the request is invalid.
#### Detected  as API Gateway Extension
Picked up JAVA_TOOL_OPTIONS: -Dgnu.io.rxtx.SerialPorts=/dev/tty96B0
2016-06-07 03:22:37,526 INFO - Using API Gateway endpoint https://apigateway.us-west-2.amazonaws.com
2016-06-07 03:22:45,896 ERROR - Error importing API definition
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.amazonaws.AmazonServiceException: The security token included in the request is invalid. (Service: null; Status Code: 403; Error Code: null; Request ID: 1a39a755-2c5f-11e6-ab04-df3157e3cab5)
  at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:63)
  while locating com.amazonaws.services.apigateway.model.ApiGateway
    for field at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkApiImporter.apiGateway(ApiGatewaySdkApiImporter.java:41)
  while locating com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter
  while locating com.amazonaws.service.apigateway.importer.SwaggerApiImporter
    for parameter 1 at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.<init>(ApiGatewaySwaggerFileImporter.java:36)
  while locating com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:143)
	at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:83)
Caused by: com.amazonaws.AmazonServiceException: The security token included in the request is invalid. (Service: null; Status Code: 403; Error Code: null; Request ID: 1a39a755-2c5f-11e6-ab04-df3157e3cab5)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1275)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:873)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
	at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
	at com.amazonaws.hal.client.HalClient.getHalResource(HalClient.java:210)
	at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:200)
	at com.amazonaws.hal.client.HalClient.getResource(HalClient.java:92)
	at com.amazonaws.hal.HalService.getRootResource(HalService.java:128)
	at com.amazonaws.services.apigateway.AmazonApiGateway.getApiGateway(AmazonApiGateway.java:113)
	at com.amazonaws.service.apigateway.importer.config.ApiImporterDefaultModule.provideAmazonApiGateway(ApiImporterDefaultModule.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:299)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 3 more
***Configuring Dashboard on S3...

A client error (UnrecognizedClientException) occurred when calling the GetRestApis operation: The security token included in the request is invalid.
#### Detected  as API Gateway Identifier
make_bucket failed: s3://dragonconnect-exteliot0003/ A client error (InvalidAccessKeyId) occurred when calling the CreateBucket operation: The AWS Access Key Id you provided does not exist in our records.

upload failed: css/bootstrap.min.css to s3://dragonconnect-exteliot0003/css/bootstrap.min.css A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: css/font-awesome.min.css to s3://dragonconnect-exteliot0003/css/font-awesome.min.css A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: css/font-awesome.css to s3://dragonconnect-exteliot0003/css/font-awesome.css A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: css/bootstrap-theme.css.map to s3://dragonconnect-exteliot0003/css/bootstrap-theme.css.map A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: css/styles.css to s3://dragonconnect-exteliot0003/css/styles.css A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: css/bootstrap-theme.min.css to s3://dragonconnect-exteliot0003/css/bootstrap-theme.min.css A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: css/bootstrap.css to s3://dragonconnect-exteliot0003/css/bootstrap.css A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: css/bootstrap-theme.css to s3://dragonconnect-exteliot0003/css/bootstrap-theme.css A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: css/bootstrap.css.map to s3://dragonconnect-exteliot0003/css/bootstrap.css.map A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: css/db.css to s3://dragonconnect-exteliot0003/css/db.css A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/FontAwesome.otf to s3://dragonconnect-exteliot0003/fonts/FontAwesome.otf A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/fontawesome-webfont.svg to s3://dragonconnect-exteliot0003/fonts/fontawesome-webfont.svg A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/fontawesome-webfont.ttf to s3://dragonconnect-exteliot0003/fonts/fontawesome-webfont.ttf A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/fontawesome-webfont.eot to s3://dragonconnect-exteliot0003/fonts/fontawesome-webfont.eot A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/fontawesome-webfont.woff to s3://dragonconnect-exteliot0003/fonts/fontawesome-webfont.woff A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/glyphicons-halflings-regular.eot to s3://dragonconnect-exteliot0003/fonts/glyphicons-halflings-regular.eot A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/fontawesome-webfont.woff2 to s3://dragonconnect-exteliot0003/fonts/fontawesome-webfont.woff2 A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/glyphicons-halflings-regular.ttf to s3://dragonconnect-exteliot0003/fonts/glyphicons-halflings-regular.ttf A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/glyphicons-halflings-regular.svg to s3://dragonconnect-exteliot0003/fonts/glyphicons-halflings-regular.svg A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/glyphicons-halflings-regular.woff to s3://dragonconnect-exteliot0003/fonts/glyphicons-halflings-regular.woff A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: fonts/glyphicons-halflings-regular.woff2 to s3://dragonconnect-exteliot0003/fonts/glyphicons-halflings-regular.woff2 A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/ajax-loader.gif to s3://dragonconnect-exteliot0003/gfxs/ajax-loader.gif A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/dragon-connect-logo@2x.png to s3://dragonconnect-exteliot0003/gfxs/dragon-connect-logo@2x.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/board.png to s3://dragonconnect-exteliot0003/gfxs/board.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/dragon-sense-logo@2x.png to s3://dragonconnect-exteliot0003/gfxs/dragon-sense-logo@2x.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/dragonboard410c_logo.png to s3://dragonconnect-exteliot0003/gfxs/dragonboard410c_logo.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/dragonboard410c_logo_bs.png to s3://dragonconnect-exteliot0003/gfxs/dragonboard410c_logo_bs.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/search.jpg to s3://dragonconnect-exteliot0003/gfxs/search.jpg A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/ready_to_fuel.png to s3://dragonconnect-exteliot0003/gfxs/ready_to_fuel.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/dragonpulse-logo@2x.png to s3://dragonconnect-exteliot0003/gfxs/dragonpulse-logo@2x.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/sprites-bulb@2x.png to s3://dragonconnect-exteliot0003/gfxs/sprites-bulb@2x.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/sprites-sensor@2x.png to s3://dragonconnect-exteliot0003/gfxs/sprites-sensor@2x.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/sprites-volume@2x.png to s3://dragonconnect-exteliot0003/gfxs/sprites-volume@2x.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/volume-bg-lg.jpg to s3://dragonconnect-exteliot0003/gfxs/volume-bg-lg.jpg A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/sprites@2x.png to s3://dragonconnect-exteliot0003/gfxs/sprites@2x.png A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/volume-bg-md.jpg to s3://dragonconnect-exteliot0003/gfxs/volume-bg-md.jpg A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/volume-bg-sm.jpg to s3://dragonconnect-exteliot0003/gfxs/volume-bg-sm.jpg A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: gfxs/volume-bg-xs.jpg to s3://dragonconnect-exteliot0003/gfxs/volume-bg-xs.jpg A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: js/bootstrap.js to s3://dragonconnect-exteliot0003/js/bootstrap.js A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: ./index.html to s3://dragonconnect-exteliot0003/index.html A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: js/bootstrap.min.js to s3://dragonconnect-exteliot0003/js/bootstrap.min.js A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: js/config.js to s3://dragonconnect-exteliot0003/js/config.js A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: js/config_template.js to s3://dragonconnect-exteliot0003/js/config_template.js A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: js/dragonconnect.js to s3://dragonconnect-exteliot0003/js/dragonconnect.js A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: js/moment.min.js to s3://dragonconnect-exteliot0003/js/moment.min.js A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: js/npm.js to s3://dragonconnect-exteliot0003/js/npm.js A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: things/lambdaTest/audio.json to s3://dragonconnect-exteliot0003/things/lambdaTest/audio.json A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: things/lambdaTest/led.json to s3://dragonconnect-exteliot0003/things/lambdaTest/led.json A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: things/things.json to s3://dragonconnect-exteliot0003/things/things.json A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
upload failed: js/jquery-1.11.1.min.js to s3://dragonconnect-exteliot0003/js/jquery-1.11.1.min.js A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

***Configuring Bucket Policy on S3...

A client error (InvalidAccessKeyId) occurred when calling the PutBucketPolicy operation: The AWS Access Key Id you provided does not exist in our records.

A client error (InvalidAccessKeyId) occurred when calling the PutBucketWebsite operation: The AWS Access Key Id you provided does not exist in our records.
***Provisioning a Thing...
ERROR
  Message: Policy DragonConnect must exist before creating a thing
#### Detected 567ba9c33b2f4e64b4c3a8404f3017a1 as Thing ID
***Installing Certificates for the Device...
cp: cannot stat ‘/home/linaro/Documents/registry/567ba9c33b2f4e64b4c3a8404f3017a1/aws.key’: No such file or directory
cp: cannot stat ‘/home/linaro/Documents/registry/567ba9c33b2f4e64b4c3a8404f3017a1/aws.crt’: No such file or directory
***Building Client...

Regards, Henry

**Comment by hlkn** [comment]
I believe I know the issue - One MUST login as root account to perform the installation tasks... Not as an IAM account....
